spring:
  application:
    name: epita-cloud
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI:}

aws:
  dynamodb:
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}
    endpoint: ${DYNAMODB_ENDPOINT:}
    region: ${AWS_REGION:eu-west-3}
